services:
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - userdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d userdb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - micro-net

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"
    volumes:
      - orderdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order -d orderdb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - micro-net

  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_USER: payuser
      POSTGRES_PASSWORD: paypassword
      POSTGRES_DB: paymentdb
    ports:
      - "5434:5432"
    volumes:
      - paymentdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payuser -d paymentdb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - micro-net

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5435:5432"
    volumes:
      - authdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d userdb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - micro-net

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - micro-net
    environment:
      JWT_SECRET: ItsSecretcomposer

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - order-db
      - user-service
    networks:
      - micro-net

  payment-service:
    build: ./payment-service
    ports:
      - "8083:8083"
    depends_on:
      - payment-db
      - order-service
    environment:
      ORDER_SERVICE_URL: http://order-service:8082
      PAYMENT_DB_URL: postgres://payuser:paypassword@payment-db:5432/paymentdb?sslmode=disable
    networks:
      - micro-net

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"
    depends_on:
      - payment-service
      - order-service
    networks:
      - micro-net
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBIT_MQ_URL: amqp://guest:guest@rabbitmq:5672/
    networks:
      - micro-net

  auth-service:
    build: ./auth-service
    ports:
      - "8085:8085"
    depends_on:
      - auth-db
    networks:
      - micro-net
    environment:
      AUTH_DB_URL: postgres://authuser:authpass@auth-db:5432/authdb?sslmode=disable
      JWT_SECRET: ItsSecretcomposer
  
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ItsSecretcomposer
    networks:
      - micro-net

volumes:
  userdb-data: {}
  orderdb-data: {}
  paymentdb-data: {}
  authdb-data: {}
networks:
  micro-net:
    driver: bridge
